# Generated by Django 3.1.3 on 2020-11-08 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Censor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toCensor', models.CharField(max_length=30)),
                ('censorWith', models.CharField(max_length=30)),
            ],
        ),
    ]
